-- Switch ON every case of DalaTech test set (53 cases, tenant «dalatech»).
-- GENERATED by scripts/replycases/sql.ts from scripts/bakeoff/dalatech-set.json.
--
-- Run this ONLY when docs/reports/dalatech-testset.md says every case passed AND the founder's read agrees.
-- Otherwise run the narrower statement that report prints: an active case that fails
-- blocks every production build and every publish (D-120).
update reply_cases set active = true
 where tenant_id = (select id from tenants where slug = 'dalatech')
   and active = false
   and split_part(note, ' ', 1) in ('dalatech-testset:i01', 'dalatech-testset:i02', 'dalatech-testset:i03', 'dalatech-testset:i04', 'dalatech-testset:p01', 'dalatech-testset:p02', 'dalatech-testset:p03', 'dalatech-testset:p04', 'dalatech-testset:q01', 'dalatech-testset:q02', 'dalatech-testset:q03', 'dalatech-testset:q04', 'dalatech-testset:q05', 'dalatech-testset:w01', 'dalatech-testset:w02', 'dalatech-testset:w03', 'dalatech-testset:w04', 'dalatech-testset:w05', 'dalatech-testset:x01', 'dalatech-testset:x02', 'dalatech-testset:x03', 'dalatech-testset:s01', 'dalatech-testset:s02', 'dalatech-testset:s03', 'dalatech-testset:s04', 'dalatech-testset:l01', 'dalatech-testset:l02', 'dalatech-testset:l03', 'dalatech-testset:l04', 'dalatech-testset:o01', 'dalatech-testset:o02', 'dalatech-testset:m01', 'dalatech-testset:m02', 'dalatech-testset:m03', 'dalatech-testset:e01', 'dalatech-testset:e02', 'dalatech-testset:k01', 'dalatech-testset:k02', 'dalatech-testset:k03', 'dalatech-testset:c01', 'dalatech-testset:c02', 'dalatech-testset:t01', 'dalatech-testset:t02', 'dalatech-testset:r01', 'dalatech-testset:n01', 'dalatech-testset:n02', 'dalatech-testset:j01', 'dalatech-testset:f01', 'dalatech-testset:v01', 'dalatech-testset:v02', 'dalatech-testset:v03', 'dalatech-testset:v04', 'dalatech-testset:v05');
