-- DalaTech salesperson test set: 15 reply cases for tenant «dalatech», INACTIVE (D-120).
-- GENERATED by scripts/replycases/sql.ts from scripts/bakeoff/dalatech-sales-set.json — edit the set, then regenerate; a unit test fails on drift.
--
-- The order, and none of it may be skipped:
--   1. Apply this file. Every row goes in with active = false, so nothing gates a deploy yet.
--   2. Run the set: node scripts/bakeoff/testset.ts (see scripts/bakeoff/README.md).
--      It answers every case through the production reply path and writes docs/reports/dalatech-sales-testset.md.
--   3. The founder reads every reply in that report.
--   4. Activate — with the statement the report prints, which names only the cases that
--      PASSED. The activation file beside this one switches on every case and is right
--      only when the report says every case passed.
-- An active case that fails blocks every production build and every publish.
begin;

do $$
begin
  if not exists (select 1 from tenants where slug = 'dalatech') then
    raise exception 'no tenant with slug dalatech';
  end if;
end
$$;

-- sp1 · price
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'үнэ хэд вэ',
       'Сарын төлбөр: Дали 250,000₮, Вира 150,000₮, Эхо 250,000₮, Нова 150,000₮, Ора 250,000₮. Нэг удаагийн суурилуулалт: Дали 150,000₮, Вира 150,000₮, Эхо 200,000₮, Нова 150,000₮, Ора 150,000₮. Вира, Эхо, Нова, Ора хараахан ажиллаж эхлээгүй бөгөөд урьдчилан бүртгүүлж болно.
Вэбсайт: Ухаалаг вэбсайт 750,000₮, Вэбсайт + Дали багц 800,000₮.

🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.
🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online
👉 Бусад AI ажилтнууд: https://dalatech.online',
       '{}'::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sp1 — The price_overview row, then the approved follow-up, exactly.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sp1');

-- sp2 · price
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Дали сард хэд вэ?',
       null,
       array['💬 Дали', '💰 Сарын төлбөр: 250,000₮', '24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'Бусад AI ажилтнууд: https://dalatech.online']::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sp2 — Дали''s monthly price in the approved look («💬 Дали — AI хүлээн авагч» / «💰 Сарын төлбөр: 250,000₮»), then the approved follow-up.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sp2');

-- sq2 · second
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[{"role":"user","content":"үнэ хэд вэ"},{"role":"assistant","content":"Сарын төлбөр: Дали 250,000₮, Вира 150,000₮, Эхо 250,000₮, Нова 150,000₮, Ора 250,000₮. Нэг удаагийн суурилуулалт: Дали 150,000₮, Вира 150,000₮, Эхо 200,000₮, Нова 150,000₮, Ора 150,000₮. Вира, Эхо, Нова, Ора хараахан ажиллаж эхлээгүй бөгөөд урьдчилан бүртгүүлж болно.\nВэбсайт: Ухаалаг вэбсайт 750,000₮, Вэбсайт + Дали багц 800,000₮.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online"}]'::jsonb, 'Хэр хурдан ажиллаж эхлэх вэ?',
       null,
       array['долоо хоног']::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sq2 — The answer to the second question, with NO second follow-up: once per conversation.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sq2');

-- sq3 · second
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[{"role":"user","content":"үнэ хэд вэ"},{"role":"assistant","content":"Сарын төлбөр: Дали 250,000₮, Вира 150,000₮, Эхо 250,000₮, Нова 150,000₮, Ора 250,000₮. Нэг удаагийн суурилуулалт: Дали 150,000₮, Вира 150,000₮, Эхо 200,000₮, Нова 150,000₮, Ора 150,000₮. Вира, Эхо, Нова, Ора хараахан ажиллаж эхлээгүй бөгөөд урьдчилан бүртгүүлж болно.\nВэбсайт: Ухаалаг вэбсайт 750,000₮, Вэбсайт + Дали багц 800,000₮.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online"}]'::jsonb, 'Вэбсайт хийхэд хэр удах вэ?',
       null,
       array['ажлын өдөр']::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sq3 — A second question about the website: answered, no second follow-up.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sq3');

-- sg1 · greeting
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Сайн байна уу',
       'Сайн байна уу! Би DalaTech-ийн AI туслах Дали байна. AI ажилтан, вэбсайтын талаар хүссэн зүйлээ асуугаарай.',
       '{}'::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'app.dalatech.online', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sg1 — A short greeting only: the approved introduction, exactly. No other product name (a live reply called us «Дала апп»), no coming-soon line, no sales line.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sg1');

-- sg2 · greeting
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'sain bnuu',
       'Сайн байна уу! Би DalaTech-ийн AI туслах Дали байна. AI ажилтан, вэбсайтын талаар хүссэн зүйлээ асуугаарай.',
       '{}'::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'app.dalatech.online', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sg2 — A Latin greeting alone: the approved introduction, exactly, and no sales line.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sg2');

-- st1 · thanks
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Баярлалаа',
       'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.',
       '{}'::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'app.dalatech.online', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:st1 — A thanks alone: the approved reply to thanks, exactly (founder, 2026-09-26: «Тавтай морил!» was wrong, it welcomes an arrival). No sales line.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:st1');

-- sc1 · complaint
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Та нар яагаад хариулахгүй байгаа юм бэ, муухай үйлчилгээ',
       null,
       array['Уучлаарай']::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'app.dalatech.online', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sc1 — A complaint: an apology, never a sales line.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sc1');

-- sd1 · demo
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Демо үзмээр байна',
       'Өөрийн бизнест зориулсан демог https://app.dalatech.online хаягаар захиалж болно. Эсвэл нэр, утасны дугаараа энд бичиж үлдээвэл хамт олон маань тантай холбогдоно.',
       '{}'::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sd1 — Asks for a demo, and only that: the approved demo line, exactly, with no model call.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sd1');

-- sd2 · demo
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'turshij uzej boloh uu',
       'Өөрийн бизнест зориулсан демог https://app.dalatech.online хаягаар захиалж болно. Эсвэл нэр, утасны дугаараа энд бичиж үлдээвэл хамт олон маань тантай холбогдоно.',
       '{}'::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sd2 — Asks for a demo, and only that: the approved demo line, exactly, with no model call.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sd2');

-- sk1 · call
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Надад залгаж болох уу?',
       null,
       array['Нэр, утасны дугаараа энд бичиж үлдээвэл хамт олон маань тантай холбогдоно.']::text[],
       array['24/7 хариулна', 'Үнэгүй демо, 24 цагт бэлэн', 'Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sk1 — Asks for a call: the approved callback line, not the general follow-up.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sk1');

-- sn1 · number
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Намайг Бат гэдэг, 99112233',
       'Баярлалаа! Мэдээллийг тань хүлээн авлаа. Хамт олон маань тантай холбогдоно.',
       '{}'::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sn1 — Leaves a name and number: the approved lead_thanks line, exactly, with no model call.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sn1');

-- sn2 · number
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, '99112233 руу залгаарай',
       'Баярлалаа! Мэдээллийг тань хүлээн авлаа. Хамт олон маань тантай холбогдоно.',
       '{}'::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sn2 — A number with ''call me'': still the lead_thanks line.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sn2');

-- sw1 · question
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Сайн байна уу, Дали юу хийдэг вэ?',
       null,
       array['хүлээн авагч', '24/7 хариулна']::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sw1 — A greeting WITH a question is a question: answered, then the follow-up.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sw1');

-- sd3 · demo
insert into reply_cases (tenant_id, history, customer_message, expected_body, must_include, must_not_include, note, active)
select t.id, '[]'::jsonb, 'Демо хэдэн цагт бэлэн болох вэ?',
       null,
       array['app.dalatech.online']::text[],
       array['Матрикс', 'Matrix', 'Tara', 'Тара салон', 'манай салон', 'салонд тавтай', 'үс засалт', 'дотоод заавар', 'БЭЛЭН ХАРИУЛТ', '76001888', '7741-7777', '80905498', 'Вира одоо ажиллаж байна', 'Эхо одоо ажиллаж байна', 'Нова одоо ажиллаж байна', 'Ора одоо ажиллаж байна', 'Вира одоо ажиллаж байгаа', 'Эхо одоо ажиллаж байгаа', 'Нова одоо ажиллаж байгаа', 'Ора одоо ажиллаж байгаа', 'Вира идэвхтэй ажиллаж байна', 'Эхо идэвхтэй ажиллаж байна', 'Нова идэвхтэй ажиллаж байна', 'Ора идэвхтэй ажиллаж байна', 'Вира идэвхтэй байна', 'Эхо идэвхтэй байна', 'Нова идэвхтэй байна', 'Ора идэвхтэй байна', 'Дали хараахан ажиллаж эхлээгүй', 'Дали одоогоор ажиллаж эхлээгүй', 'Дали ажиллаж эхлээгүй']::text[],
       'dalatech-sales:sd3 — A question ABOUT the demo, not just a request: answered by the model, and it names the demo page.', false
from tenants t where t.slug = 'dalatech'
  and not exists (select 1 from reply_cases r where r.tenant_id = t.id and split_part(r.note, ' ', 1) = 'dalatech-sales:sd3');

commit;
