-- Switch ON every case of DalaTech salesperson test set (14 cases, tenant «dalatech»).
-- GENERATED by scripts/replycases/sql.ts from scripts/bakeoff/dalatech-sales-set.json.
--
-- Run this ONLY when docs/reports/dalatech-sales-testset.md says every case passed AND the founder's read agrees.
-- Otherwise run the narrower statement that report prints: an active case that fails
-- blocks every production build and every publish (D-120).
update reply_cases set active = true
 where tenant_id = (select id from tenants where slug = 'dalatech')
   and active = false
   and split_part(note, ' ', 1) in ('dalatech-sales:sp1', 'dalatech-sales:sp2', 'dalatech-sales:sq2', 'dalatech-sales:sq3', 'dalatech-sales:sg1', 'dalatech-sales:sg2', 'dalatech-sales:st1', 'dalatech-sales:sc1', 'dalatech-sales:sd1', 'dalatech-sales:sd2', 'dalatech-sales:sk1', 'dalatech-sales:sn1', 'dalatech-sales:sn2', 'dalatech-sales:sw1');
