-- 29 comment rules from templates/comment_rules.software.json for tenant dalatech
begin;
update comment_rules set enabled = false
 where tenant_id = (select id from tenants where slug = $r$dalatech$r$)
   and rule_key not in ($r$complaint$r$, $r$complaint_phrases$r$, $r$complaint_phrases_lat$r$, $r$complaint_call_mn$r$, $r$complaint_call_lat$r$, $r$complaint_days_mn$r$, $r$complaint_days_lat$r$, $r$complaint_money_mn$r$, $r$complaint_money_lat$r$, $r$complaint_human_mn$r$, $r$complaint_human_lat$r$, $r$complaint_words$r$, $r$complaint_bad$r$, $r$ad_keyword$r$, $r$price$r$, $r$price_stems$r$, $r$location$r$, $r$booking$r$, $r$info$r$, $r$info_stems$r$, $r$product_question_q_word$r$, $r$product_question_q_stem$r$, $r$product_question_end_word$r$, $r$product_question_end_stem$r$, $r$any_question_mark$r$, $r$praise$r$, $r$praise_stems$r$, $r$laughter$r$, $r$greeting$r$);
insert into comment_rules (tenant_id, rule_key, verdict, matcher, enabled, provenance)
select t.id, v.rule_key, v.verdict, v.matcher, true, 'seeded'
  from tenants t, (values
  ($r$complaint$r$, $r$escalate$r$, $r${"mode":"contains_stem","stems":["гомдол","gomdol","луйвар","luivar","залилан","zalilan","залилсан","zalilsan","сүйтгэ","suitge","svitge","сүйрүүл","suiruul","шатаа","shataa","шатсан","shatsan","шатчих","shatchih","муудсан","muudsan","муудуул","muuduul","ичгүүргүй","ichguurgui","ichgvvrgvi","бүдүүлэг","buduuleg","bvdvvleg","хариулахгүй","hariulahgui","hariulahgvi","хүлээлгэ","huleelge","hvleelge","хүлээсээр","huleeseer","дундуур","dunduur","худлаа","hudlaa","муухай","muuhai","тэнэг","teneg","хогийн","hogiin"]}$r$::jsonb),
  ($r$complaint_phrases$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["утсаа","ав"],"windowCp":20}$r$::jsonb),
  ($r$complaint_phrases_lat$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["utsaa","av"],"windowCp":20}$r$::jsonb),
  ($r$complaint_call_mn$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["залга","авахгүй"],"windowCp":30}$r$::jsonb),
  ($r$complaint_call_lat$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["zalga","avahgui"],"windowCp":30}$r$::jsonb),
  ($r$complaint_days_mn$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["өдөр","залга"],"windowCp":20}$r$::jsonb),
  ($r$complaint_days_lat$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["udur","zalga"],"windowCp":20}$r$::jsonb),
  ($r$complaint_money_mn$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["мөнгө","буцаа"],"windowCp":20}$r$::jsonb),
  ($r$complaint_money_lat$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["mungu","butsaa"],"windowCp":20}$r$::jsonb),
  ($r$complaint_human_mn$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["хүнтэй","холбог"],"windowCp":20}$r$::jsonb),
  ($r$complaint_human_lat$r$, $r$escalate$r$, $r${"mode":"stem_sequence","stems":["huntei","holbog"],"windowCp":20}$r$::jsonb),
  ($r$complaint_words$r$, $r$escalate$r$, $r${"mode":"has_word","words":["ai bish","ай биш","бот биш","bot bish","хог"]}$r$::jsonb),
  ($r$complaint_bad$r$, $r$escalate$r$, $r${"mode":"all_of","matchers":[{"mode":"has_word","words":["муу","muu"]},{"mode":"not","matcher":{"mode":"has_word","words":["биш","bish","bishee","бишээ"]}}]}$r$::jsonb),
  ($r$ad_keyword$r$, $r$reply$r$, $r${"mode":"has_word","words":["message","мессеж","messege","combo","комбо"]}$r$::jsonb),
  ($r$price$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"has_word","words":["үнэ","une","vne","үнэ нь","үнийг","uniig","хэд","hed","хэдэн","heden","хэдээр","hedeer","төгрөг","tugrug","ямар үнэтэй"]},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$price_stems$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"contains_stem","stems":["үнийн","uniin","vniin","үнэтэй","unetei","vnetei","хэдээр","hedeer","төлбөр","tulbur","tolbor","хямдрал","hymdral","hyamdral","урамшуулал","uramshuulal","төгрөг","tugrug"]},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$location$r$, $r$reply$r$, $r${"mode":"contains_stem","stems":["хаяг","hayg","hayag","xayg","haig","байршил","bairshil","хаана","haana","xaana","хаашаа","haashaa","салбарууд","salbaruud"]}$r$::jsonb),
  ($r$booking$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"contains_stem","stems":["захиал","zahial","zakhial","бүртгүүл","burtguul"]},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$info$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"has_word","words":["ib","pm","dm","info","инфо","иб","пм","inbox","инбокс","дэлгэрэнгүй","delgerengui","delgerengvi","мэдээлэл","medeelel","detail","details","dtl","утас","utas","утсаа","utsaa","дугаар","dugaar","дугаараа","dugaaraa"]},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$info_stems$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"contains_stem","stems":["дэлгэрэнгүй","delgerengu","delgerengv","мэдээлэл","medeelel","medeell","инбокс","inbox","холбогд","holbogd","утасны","utasnii","дугаар","dugaar","ibee","ibeer","ибээр","pmeer","пмээр"]},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$product_question_q_word$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"has_word","words":["?","уу","үү","юу","юү","вэ","бэ","бол","uu","vv","yu","yuu","ve","we","be","bol"]},{"mode":"has_word","words":["дали","dali","вира","vira","эхо","echo","eho","нова","nova","ора","ora","ai","аи","бот","bot","сайт","site","вэб","web","чатбот","chatbot","туслах","tuslah","ажилтан","ajiltan","програм","программ","program","систем","system","автомат","avtomat"]},{"mode":"not","matcher":{"mode":"has_word","words":["гоё","гоёо","гоёоо","goy","goyo","goyoo","хөөрхөн","hoorhon","huurhun","hvvrhun","сайхан","saihan","гайхалтай","gaihaltai","мундаг","mundag","амжилт","amjilt","баярлалаа","bayarlalaa","bayrlalaa","wow","woow","вау","super","супер","nice"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["гоёмсог","хөөрхөн","гайхалт","мундаг","mundag","амжилт","amjilt","баярлал","bayarlal","bayrlal","чадварлаг","chadvarlag"]}},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$product_question_q_stem$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"has_word","words":["?","уу","үү","юу","юү","вэ","бэ","бол","uu","vv","yu","yuu","ve","we","be","bol"]},{"mode":"contains_stem","stems":["вэбсайт","website","вебсайт","websait","чатбот","chatbot","автомат","avtomat","программ","програм","program","мессенжер","messenger","инстаграм","instagram","ажилтн","ajiltn","туслах","tuslah"]},{"mode":"not","matcher":{"mode":"has_word","words":["гоё","гоёо","гоёоо","goy","goyo","goyoo","хөөрхөн","hoorhon","huurhun","hvvrhun","сайхан","saihan","гайхалтай","gaihaltai","мундаг","mundag","амжилт","amjilt","баярлалаа","bayarlalaa","bayrlalaa","wow","woow","вау","super","супер","nice"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["гоёмсог","хөөрхөн","гайхалт","мундаг","mundag","амжилт","amjilt","баярлал","bayarlal","bayrlal","чадварлаг","chadvarlag"]}},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$product_question_end_word$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"ends_with","endings":["уу","үү","юу","юү","вэ","бэ","uu","vv","yu","ve","we","be"]},{"mode":"has_word","words":["дали","dali","вира","vira","эхо","echo","eho","нова","nova","ора","ora","ai","аи","бот","bot","сайт","site","вэб","web","чатбот","chatbot","туслах","tuslah","ажилтан","ajiltan","програм","программ","program","систем","system","автомат","avtomat"]},{"mode":"not","matcher":{"mode":"has_word","words":["гоё","гоёо","гоёоо","goy","goyo","goyoo","хөөрхөн","hoorhon","huurhun","hvvrhun","сайхан","saihan","гайхалтай","gaihaltai","мундаг","mundag","амжилт","amjilt","баярлалаа","bayarlalaa","bayrlalaa","wow","woow","вау","super","супер","nice"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["гоёмсог","хөөрхөн","гайхалт","мундаг","mundag","амжилт","amjilt","баярлал","bayarlal","bayrlal","чадварлаг","chadvarlag"]}},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$product_question_end_stem$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"ends_with","endings":["уу","үү","юу","юү","вэ","бэ","uu","vv","yu","ve","we","be"]},{"mode":"contains_stem","stems":["вэбсайт","website","вебсайт","websait","чатбот","chatbot","автомат","avtomat","программ","програм","program","мессенжер","messenger","инстаграм","instagram","ажилтн","ajiltn","туслах","tuslah"]},{"mode":"not","matcher":{"mode":"has_word","words":["гоё","гоёо","гоёоо","goy","goyo","goyoo","хөөрхөн","hoorhon","huurhun","hvvrhun","сайхан","saihan","гайхалтай","gaihaltai","мундаг","mundag","амжилт","amjilt","баярлалаа","bayarlalaa","bayrlalaa","wow","woow","вау","super","супер","nice"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["гоёмсог","хөөрхөн","гайхалт","мундаг","mundag","амжилт","amjilt","баярлал","bayarlal","bayrlal","чадварлаг","chadvarlag"]}},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$any_question_mark$r$, $r$reply$r$, $r${"mode":"all_of","matchers":[{"mode":"has_word","words":["?"]},{"mode":"not","matcher":{"mode":"whole_message","phrases":["сайн байна уу","сайн уу","sain baina uu","sain bnuu","sn bnu","hi","hello","сайн байцгаана уу"]}},{"mode":"not","matcher":{"mode":"has_word","words":["гоё","гоёо","гоёоо","goy","goyo","goyoo","хөөрхөн","hoorhon","huurhun","hvvrhun","сайхан","saihan","гайхалтай","gaihaltai","мундаг","mundag","амжилт","amjilt","баярлалаа","bayarlalaa","bayrlalaa","wow","woow","вау","super","супер","nice"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["гоёмсог","хөөрхөн","гайхалт","мундаг","mundag","амжилт","amjilt","баярлал","bayarlal","bayrlal","чадварлаг","chadvarlag"]}},{"mode":"not","matcher":{"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}},{"mode":"not","matcher":{"mode":"contains_stem","stems":["хаха","хэхэ","haha","hehe","xaxa"]}}]}$r$::jsonb),
  ($r$praise$r$, $r$ignore$r$, $r${"mode":"has_word","words":["гоё","гоёо","гоёоо","goy","goyo","goyoo","хөөрхөн","hoorhon","huurhun","hvvrhun","сайхан","saihan","гайхалтай","gaihaltai","мундаг","mundag","амжилт","amjilt","баярлалаа","bayarlalaa","bayrlalaa","wow","woow","вау","super","супер","nice"]}$r$::jsonb),
  ($r$praise_stems$r$, $r$ignore$r$, $r${"mode":"contains_stem","stems":["гоёмсог","хөөрхөн","гайхалт","мундаг","mundag","амжилт","amjilt","баярлал","bayarlal","bayrlal","чадварлаг","chadvarlag"]}$r$::jsonb),
  ($r$laughter$r$, $r$ignore$r$, $r${"mode":"has_word","words":["хаха","хахаха","хэхэ","хихи","haha","hahaha","hehe","hihi","xaxa","lol","kkk","😂","🤣","😆","😅","😹"]}$r$::jsonb),
  ($r$greeting$r$, $r$ignore$r$, $r${"mode":"whole_message","phrases":["сайн байна уу","сайн уу","sain baina uu","sain bnuu","sn bnu","hi","hello","сайн байцгаана уу"]}$r$::jsonb)
  ) as v(rule_key, verdict, matcher)
 where t.slug = $r$dalatech$r$
on conflict (tenant_id, rule_key) do update
   set verdict = excluded.verdict, matcher = excluded.matcher, enabled = true;
commit;
