-- DalaTech (tenant #0): the founder's approved lines of 2026-09-27, after the live test at
-- publish seq 10 (D-149). Every Mongolian line below is the founder's, verbatim.
--
--  1. Thanks: the row already answers «Баярлалаа» with the approved line; the «Тавтай морил»
--     replies were the model's, on 2026-09-26. Six more thanks forms become exact cases.
--  2-4. Annual prepay, VAT / И-баримт and the minimum contract become deterministic rows (no
--     model, no spend), with the same words in the FAQ and the «Үнийн нөхцөл» document, so the
--     model's path (which serves a FAQ answer verbatim, `gate/pinned.ts`) says the same.
--  5. The multi-staff discount: the row, the FAQ, and no minus sign anywhere.
--  6. Demo: both demo rows.
--  7. The two coming-soon rows gain not(in_reply(«урьдчилан»)). Needs the code that judges a
--     message-matched append again against the reply (D-149): RUN THIS AFTER THAT DEPLOY, or
--     a deterministic Нова answer gets the status line appended on the old code.
--  8. «Нова юу хийдэг вэ?» gets the approved description from a row.
--
-- Rows are live on commit; the FAQ and document text reaches the model at the next publish.
begin;
create temp table dt on commit drop as select id from tenants where slug = 'dalatech';

update deterministic_replies d set body = normalize('Тийм ээ, 2 AI ажилтан авбал сарын төлбөрт 10%-ийн хөнгөлөлт эдэлнэ. 3 ажилтанд 15%, 4-өөс дээш бол 20%.', NFC) from dt where d.tenant_id = dt.id and d.intent = 'discount_overview';
update deterministic_replies d set body = normalize('Үнэгүй демо үзэх бол app.dalatech.online руу орж бизнесийнхээ мэдээллийг оруулаарай — танай вэбсайтын демо 24 цагт бэлэн болно 😊', NFC) from dt where d.tenant_id = dt.id and d.intent = 'demo_request';
update deterministic_replies d set body = normalize('Үнэгүй демо үзэх бол app.dalatech.online руу орж бизнесийнхээ мэдээллийг оруулаарай — танай вэбсайтын демо 24 цагт бэлэн болно 😊', NFC) from dt where d.tenant_id = dt.id and d.intent = 'demo_timing';
update deterministic_replies d set cover_words = d.cover_words || array['ажилтан','ажилтанд','ажилтны','ажилчин','авбал','авах','авч','хоёр','гурав','олон','2','3','4','хэд','хэдэн','ajiltan','ajiltand','avbal','avah','hoyor','gurav','olon','hed','heden']::text[] from dt where d.tenant_id = dt.id and d.intent = 'discount_overview';
update deterministic_replies d set matcher = '{"mode": "all_of", "matchers": [{"mode": "has_word", "words": ["вира", "вираг", "вирагийн", "вирад", "вираас", "веда", "vira", "virag", "viragiin", "veda", "эхо", "эхог", "эхогийн", "эхоор", "эхоос", "eho", "echo", "ehog", "ehogiin", "ehoor", "нова", "новаг", "новагийн", "новад", "новаас", "nova", "novag", "novagiin", "ора", "ораг", "орагийн", "ораар", "ораас", "ora", "orag", "oragiin"]}, {"mode": "not", "matcher": {"mode": "in_reply", "matcher": {"mode": "has_word", "words": ["урьдчилан"]}}}]}'::jsonb from dt where d.tenant_id = dt.id and d.intent = 'coming_soon_status';
update deterministic_replies d set matcher = '{"mode": "all_of", "matchers": [{"mode": "in_reply", "matcher": {"mode": "has_word", "words": ["вира", "вираг", "вирагийн", "вирад", "вираас", "эхо", "эхог", "эхогийн", "эхоор", "эхоос", "нова", "новаг", "новагийн", "новад", "новаас", "ора", "ораг", "орагийн", "ораар", "ораас"]}}, {"mode": "not", "matcher": {"mode": "in_reply", "matcher": {"mode": "has_word", "words": ["урьдчилан"]}}}]}'::jsonb from dt where d.tenant_id = dt.id and d.intent = 'coming_soon_in_reply';
insert into deterministic_replies (tenant_id, intent, body, match_mode, stems, cover_words, placement, provenance, enabled, requires_empty_history, quote_services)
select dt.id, 'annual_prepay', normalize('Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.', NFC), 'covers_message', array['жилээр','жилийн','жилд','жилээ','жилдээ','jileer','jiliin','jild','annual','yearly']::text[], array['юу','уу','үү','вэ','бэ','бий','байгаа','байна','байдаг','нь','чинь','танай','танайх','та','нар','yu','uu','ve','be','we','bii','bga','baigaa','baina','bna','baidag','bdg','ni','chini','tanai','tanaih','ta','nar','төлбөл','төлвөл','төлөх','төлбөр','төлбөрөө','урьдчилж','урьдчилан','урьдчилаад','нэг','удаа','нэгмөсөн','хямдрах','хямдардаг','хямдрал','хямдралтай','хөнгөлөлт','хөнгөлөлттэй','хөнгөлдөг','ямар','бол','тэгвэл','хэд','хэдэн','сар','сараар','авбал','авах','яах','вэ?','tulbul','tulvul','tuluh','tulbur','uridchilj','urdchilj','neg','udaa','hyamdrah','hymdrah','hungulult','hungululttei','yamar','bol','tegvel','hed','heden','sar','avbal','if','i','we','pay','per','year','for','a','discount','prepay','is','there','do','you','have']::text[], 'replace', 'tenant_confirmed', true, false, '{}'::text[] from dt
 where not exists (select 1 from deterministic_replies x where x.tenant_id = dt.id and x.intent = 'annual_prepay');
insert into deterministic_replies (tenant_id, intent, body, match_mode, stems, cover_words, placement, provenance, enabled, requires_empty_history, quote_services)
select dt.id, 'vat_receipt', normalize('Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.', NFC), 'covers_message', array['нөат','ибаримт','и-баримт','баримт','ebarimt','e-barimt','ibarimt','i-barimt','barimt','noat','nuat','vat']::text[], array['юу','уу','үү','вэ','бэ','бий','байгаа','байна','байдаг','нь','чинь','танай','танайх','та','нар','yu','uu','ve','be','we','bii','bga','baigaa','baina','bna','baidag','bdg','ni','chini','tanai','tanaih','ta','nar','и','e','i','ын','ийн','тай','орсон','орох','ордог','орно','багтсан','багтдаг','багтах','нэмэгдэх','нэмэгддэг','тооцох','тооцдог','өгөх','өгдөг','өгч','өгнө','өгөөч','гаргах','гаргадаг','гаргаж','гаргаж өгөх','авах','авч','болох','боломжтой','үнэд','үнэнд','үнэ','төлөгч','мөн','бас','хэрэгтэй','ямар','orson','oroh','ordog','ugnu','ugdug','ugch','ugh','ugukh','uguh','gargah','gargaj','boloh','bolomjtoi','une','unend','is','included','do','you','give','issue','receipt','with','the','price','in','a']::text[], 'replace', 'tenant_confirmed', true, false, '{}'::text[] from dt
 where not exists (select 1 from deterministic_replies x where x.tenant_id = dt.id and x.intent = 'vat_receipt');
insert into deterministic_replies (tenant_id, intent, body, match_mode, stems, cover_words, placement, provenance, enabled, requires_empty_history, quote_services)
select dt.id, 'contract_minimum', normalize('Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.', NFC), 'covers_message', array['гэрээ','гэрээг','гэрээний','гэрээгээ','geree','gereenii','contract']::text[], array['юу','уу','үү','вэ','бэ','бий','байгаа','байна','байдаг','нь','чинь','танай','танайх','та','нар','yu','uu','ve','be','we','bii','bga','baigaa','baina','bna','baidag','bdg','ni','chini','tanai','tanaih','ta','nar','хэдэн','хэд','сар','сараар','сарын','сараас','хугацаа','хугацаатай','хугацаанд','доод','хамгийн','багадаа','бага','наад','зах','хийх','хийдэг','байгуулах','байгуулдаг','цуцлах','цуцалж','цуцлах','болох','болно','ямар','урт','heden','hed','sar','saraar','sariin','hugatsaa','hugatsaatai','dood','hamgiin','bagadaa','baga','tsutslah','boloh','yamar','how','long','is','the','minimum','months','month','term','of']::text[], 'replace', 'tenant_confirmed', true, false, '{}'::text[] from dt
 where not exists (select 1 from deterministic_replies x where x.tenant_id = dt.id and x.intent = 'contract_minimum');
insert into deterministic_replies (tenant_id, intent, body, match_mode, stems, cover_words, placement, provenance, enabled, requires_empty_history, quote_services)
select dt.id, 'nova_about', normalize('Нова бол цаг захиалгын сануулгыг SMS-ээр илгээж, ТИЙМ/ҮГҮЙ хариуг хүлээн авдаг AI ажилтан. Одоогоор урьдчилан бүртгэл авч байна.', NFC), 'covers_message', array['нова','новаг','новагийн','nova','novag','novagiin']::text[], array['юу','уу','үү','вэ','бэ','бий','байгаа','байна','байдаг','нь','чинь','танай','танайх','та','нар','yu','uu','ve','be','we','bii','bga','baigaa','baina','bna','baidag','bdg','ni','chini','tanai','tanaih','ta','nar','хийдэг','хийх','хийнэ','гэж','гэдэг','хэн','ямар','ажилтан','ажил','тухай','талаар','мэдээлэл','дэлгэрэнгүй','тайлбарла','тайлбарлаач','хэлээч','гэсэн','hiideg','hiih','gej','gedeg','hen','yamar','ajiltan','ajil','tuhai','talaar','what','is','does','do','who','about','tell','me']::text[], 'replace', 'tenant_confirmed', true, false, '{}'::text[] from dt
 where not exists (select 1 from deterministic_replies x where x.tenant_id = dt.id and x.intent = 'nova_about');
update faqs f set answer = normalize('Тийм ээ, 2 AI ажилтан авбал сарын төлбөрт 10%-ийн хөнгөлөлт эдэлнэ. 3 ажилтанд 15%, 4-өөс дээш бол 20%.', NFC), provenance = 'tenant_confirmed' from dt where f.tenant_id = dt.id and f.question = normalize('Багийн хөнгөлөлт байдаг уу?', NFC);
update faqs f set answer = normalize('Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.', NFC), provenance = 'tenant_confirmed' from dt where f.tenant_id = dt.id and f.question = normalize('Жилээр төлбөл хөнгөлөлттэй юу?', NFC);
update faqs f set answer = normalize('Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.', NFC), provenance = 'tenant_confirmed' from dt where f.tenant_id = dt.id and f.question = normalize('Гэрээний доод хугацаа хэд вэ?', NFC);
update faqs f set answer = normalize('Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.', NFC), provenance = 'tenant_confirmed' from dt where f.tenant_id = dt.id and f.question = normalize('Үнэд НӨАТ орсон уу?', NFC);
update knowledge_documents k set body = replace(k.body, normalize('- Жилийн төлбөрөө урьдчилж төлбөл 10 сарын төлбөрөөр 12 сар ажиллуулна.', NFC), normalize('- Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.', NFC)), source = 'founder 2026-09-27', updated_at = now() from dt where k.tenant_id = dt.id and k.title = normalize('Үнийн нөхцөл', NFC);
update knowledge_documents k set body = replace(k.body, normalize('- Гэрээний доод хугацаа 3 сар.', NFC), normalize('- Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.', NFC)), source = 'founder 2026-09-27', updated_at = now() from dt where k.tenant_id = dt.id and k.title = normalize('Үнийн нөхцөл', NFC);
update knowledge_documents k set body = replace(k.body, normalize('- Манай үнэд НӨАТ нэмэгдэхгүй: DalaTech НӨАТ төлөгчөөр бүртгэлгүй.', NFC), normalize('- Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.', NFC)), source = 'founder 2026-09-27', updated_at = now() from dt where k.tenant_id = dt.id and k.title = normalize('Үнийн нөхцөл', NFC);
update knowledge_documents k set body = replace(k.body, normalize('- Цаг захиалгын сануулгыг SMS-ээр илгээж, ТИЙМ/ҮГҮЙ хариуг хүлээн авна.', NFC), normalize('- Нова бол цаг захиалгын сануулгыг SMS-ээр илгээж, ТИЙМ/ҮГҮЙ хариуг хүлээн авдаг AI ажилтан. Одоогоор урьдчилан бүртгэл авч байна.', NFC)), source = 'founder 2026-09-27', updated_at = now() from dt where k.tenant_id = dt.id and k.title = normalize('Нова — Сануулга, SMS (УДАХГҮЙ, урьдчилан бүртгэл авч байна)', NFC);
update reply_cases r set active = false from dt where r.tenant_id = dt.id and r.active and r.expected_body is null and r.customer_message in (normalize('Жилээр төлбөл хямдрах уу?', NFC), normalize('НӨАТ орсон уу?', NFC), normalize('Гэрээ хамгийн багадаа хэдэн сар вэ?', NFC));
update reply_cases r set expected_body = normalize('Үнэгүй демо үзэх бол app.dalatech.online руу орж бизнесийнхээ мэдээллийг оруулаарай — танай вэбсайтын демо 24 цагт бэлэн болно 😊', NFC) from dt where r.tenant_id = dt.id and r.active and r.expected_body is not null and r.customer_message in (normalize('Демо үзмээр байна', NFC), normalize('turshij uzej boloh uu', NFC));
insert into reply_cases (tenant_id, channel, customer_message, expected_body, note, active) values
  ((select id from dt), 'facebook_page', normalize('Баярлалаа!', NFC), normalize(E'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.', NFC), 'D-149 founder 2026-09-27: thanks, exact', true),
  ((select id from dt), 'facebook_page', normalize('За баярлалаа', NFC), normalize(E'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.', NFC), 'D-149 founder 2026-09-27: thanks, exact', true),
  ((select id from dt), 'facebook_page', normalize('баярлалаа 🙏', NFC), normalize(E'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.', NFC), 'D-149 founder 2026-09-27: thanks, exact', true),
  ((select id from dt), 'facebook_page', normalize('Bayarlalaa', NFC), normalize(E'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.', NFC), 'D-149 founder 2026-09-27: thanks, exact', true),
  ((select id from dt), 'facebook_page', normalize('thanks', NFC), normalize(E'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.', NFC), 'D-149 founder 2026-09-27: thanks, exact', true),
  ((select id from dt), 'facebook_page', normalize('Их баярлалаа', NFC), normalize(E'Зүгээр ээ 😊 Өөр асуух зүйл байвал бичээрэй.', NFC), 'D-149 founder 2026-09-27: thanks, exact', true),
  ((select id from dt), 'facebook_page', normalize('жилээр төлбөл?', NFC), normalize(E'Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: annual, exact', true),
  ((select id from dt), 'facebook_page', normalize('Жилээр төлбөл хямдрах уу?', NFC), normalize(E'Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: annual, exact', true),
  ((select id from dt), 'facebook_page', normalize('Жилийн төлбөр урьдчилж төлбөл хөнгөлөлттэй юу?', NFC), normalize(E'Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: annual, exact', true),
  ((select id from dt), 'facebook_page', normalize('jileer tulbul hyamdrah uu', NFC), normalize(E'Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: annual, exact', true),
  ((select id from dt), 'facebook_page', normalize('НӨАТ орсон уу?', NFC), normalize(E'Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: vat, exact', true),
  ((select id from dt), 'facebook_page', normalize('НӨАТ-ын баримт өгөх үү?', NFC), normalize(E'Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: vat, exact', true),
  ((select id from dt), 'facebook_page', normalize('И-баримт өгдөг үү?', NFC), normalize(E'Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: vat, exact', true),
  ((select id from dt), 'facebook_page', normalize('ebarimt ugdug uu', NFC), normalize(E'Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: vat, exact', true),
  ((select id from dt), 'facebook_page', normalize('Үнэд НӨАТ орсон уу?', NFC), normalize(E'Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: vat, exact', true),
  ((select id from dt), 'facebook_page', normalize('И-баримт', NFC), normalize(E'Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: vat, exact', true),
  ((select id from dt), 'facebook_page', normalize('гэрээ хэдэн сар?', NFC), normalize(E'Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: contract, exact', true),
  ((select id from dt), 'facebook_page', normalize('Гэрээ хамгийн багадаа хэдэн сар вэ?', NFC), normalize(E'Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: contract, exact', true),
  ((select id from dt), 'facebook_page', normalize('Гэрээний хугацаа хэд вэ?', NFC), normalize(E'Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: contract, exact', true),
  ((select id from dt), 'facebook_page', normalize('Хөнгөлөлт байгаа юу?', NFC), normalize(E'Тийм ээ, 2 AI ажилтан авбал сарын төлбөрт 10%-ийн хөнгөлөлт эдэлнэ. 3 ажилтанд 15%, 4-өөс дээш бол 20%.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: discount, exact', true),
  ((select id from dt), 'facebook_page', normalize('2 ажилтан авбал хямдрах уу?', NFC), normalize(E'Тийм ээ, 2 AI ажилтан авбал сарын төлбөрт 10%-ийн хөнгөлөлт эдэлнэ. 3 ажилтанд 15%, 4-өөс дээш бол 20%.\n\n🤖 Таны Facebook, Instagram, вэбсайтын зурваст 24/7 хариулна.\n🎁 Үнэгүй демо, 24 цагт бэлэн: https://app.dalatech.online\n👉 Бусад AI ажилтнууд: https://dalatech.online', NFC), 'D-149 founder 2026-09-27: discount, exact', true),
  ((select id from dt), 'facebook_page', normalize('Үнэгүй демо байгаа юу?', NFC), normalize(E'Үнэгүй демо үзэх бол app.dalatech.online руу орж бизнесийнхээ мэдээллийг оруулаарай — танай вэбсайтын демо 24 цагт бэлэн болно 😊', NFC), 'D-149 founder 2026-09-27: demo, exact', true),
  ((select id from dt), 'facebook_page', normalize('Демо үзмээр байна', NFC), normalize(E'Үнэгүй демо үзэх бол app.dalatech.online руу орж бизнесийнхээ мэдээллийг оруулаарай — танай вэбсайтын демо 24 цагт бэлэн болно 😊', NFC), 'D-149 founder 2026-09-27: demo, exact', true),
  ((select id from dt), 'facebook_page', normalize('Нова юу хийдэг вэ?', NFC), normalize(E'Нова бол цаг захиалгын сануулгыг SMS-ээр илгээж, ТИЙМ/ҮГҮЙ хариуг хүлээн авдаг AI ажилтан. Одоогоор урьдчилан бүртгэл авч байна.\n\nНэр, утасны дугаараа энд бичиж үлдээвэл хамт олон маань тантай холбогдоно.', NFC), 'D-149 founder 2026-09-27: nova, exact', true),
  ((select id from dt), 'facebook_page', normalize('Нова гэж юу вэ?', NFC), normalize(E'Нова бол цаг захиалгын сануулгыг SMS-ээр илгээж, ТИЙМ/ҮГҮЙ хариуг хүлээн авдаг AI ажилтан. Одоогоор урьдчилан бүртгэл авч байна.\n\nНэр, утасны дугаараа энд бичиж үлдээвэл хамт олон маань тантай холбогдоно.', NFC), 'D-149 founder 2026-09-27: nova, exact', true),
  ((select id from dt), 'facebook_page', normalize('nova yu hiideg ve', NFC), normalize(E'Нова бол цаг захиалгын сануулгыг SMS-ээр илгээж, ТИЙМ/ҮГҮЙ хариуг хүлээн авдаг AI ажилтан. Одоогоор урьдчилан бүртгэл авч байна.\n\nНэр, утасны дугаараа энд бичиж үлдээвэл хамт олон маань тантай холбогдоно.', NFC), 'D-149 founder 2026-09-27: nova, exact', true);

do $$ declare n int; begin
  select count(*) into n from deterministic_replies d join tenants t on t.id = d.tenant_id
   where t.slug = 'dalatech' and d.intent in ('annual_prepay','vat_receipt','contract_minimum','nova_about');
  if n <> 4 then raise exception 'expected 4 new rows, found %', n; end if;
  if exists (select 1 from deterministic_replies d join tenants t on t.id = d.tenant_id
              where t.slug = 'dalatech' and d.enabled and d.body like '%−%') then raise exception 'a row still writes a minus sign'; end if;
  if exists (select 1 from faqs f join tenants t on t.id = f.tenant_id
              where t.slug = 'dalatech' and f.answer like '%−%') then raise exception 'a FAQ still writes a minus sign'; end if;
  select count(*) into n from knowledge_documents k join tenants t on t.id = k.tenant_id
   where t.slug = 'dalatech' and k.body like '%2 сар үнэгүй%' and k.body like '%30 хоногийн өмнө%' and k.body like '%И-баримт%';
  if n <> 1 then raise exception 'Үнийн нөхцөл does not carry all three approved lines'; end if;
  select count(*) into n from knowledge_documents k join tenants t on t.id = k.tenant_id
   where t.slug = 'dalatech' and k.body like '%ТИЙМ/ҮГҮЙ хариуг хүлээн авдаг AI ажилтан%';
  if n <> 1 then raise exception 'Нова''s document does not carry the approved line'; end if;
  if (select count(*) from faqs f join tenants t on t.id = f.tenant_id where t.slug = 'dalatech' and f.answer in (normalize('Тийм ээ, 2 AI ажилтан авбал сарын төлбөрт 10%-ийн хөнгөлөлт эдэлнэ. 3 ажилтанд 15%, 4-өөс дээш бол 20%.', NFC), normalize('Жилийн төлбөрөө урьдчилан төлбөл 2 сар үнэгүй — 10 сарын төлбөрөөр 12 сар ажиллуулна. Энэ хөнгөлөлтийг бусад хөнгөлөлттэй хамт тооцохгүй.', NFC), normalize('Гэрээний доод хугацаа 3 сар байдаг. Үүний дараа сар бүр үргэлжлүүлэх, эсвэл 30 хоногийн өмнө мэдэгдэж цуцлах боломжтой.', NFC), normalize('Уучлаарай, манайх одоогоор НӨАТ-ын баримт (И-баримт) өгөх боломжгүй байгаа. Үнэд НӨАТ нэмж тооцогдохгүй тул таны төлөх дүн яг үнийн дүнтэй адил байна.', NFC))) <> 4 then
    raise exception 'not all four FAQ answers were replaced';
  end if;
end $$;
commit;
