/**
 * Write a test set's `reply_cases` SQL: the inactive inserts and the one-statement activation.
 *
 *     node scripts/replycases/sql.ts --set scripts/bakeoff/dalatech-set.json
 *
 * Writes the two files the set names (`sql`, `activation_sql`). Prints nothing it did not
 * write. Makes no database connection: applying the files is the founder's, in the SQL
 * editor, in the order the insert file's header gives. `sql.test.ts` fails when a committed
 * file differs from what this would write, so the set and its rows cannot drift apart.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { parseSet, renderActivationSql, renderSql, type TestSet } from './set.ts';

export function generatedBy(setPath: string): string {
  return `scripts/replycases/sql.ts from ${setPath}`;
}

export function activationFile(set: TestSet, setPath: string): string {
  return [
    `-- Switch ON every case of ${set.title} (${set.cases.length} cases, tenant «${set.tenantSlug}»).`,
    `-- GENERATED by ${generatedBy(setPath)}.`,
    '--',
    `-- Run this ONLY when ${set.report} says every case passed AND the founder's read agrees.`,
    '-- Otherwise run the narrower statement that report prints: an active case that fails',
    '-- blocks every production build and every publish (D-120).',
    renderActivationSql(set).trimEnd(),
    '',
  ].join('\n');
}

export function loadSet(setPath: string): TestSet {
  const parsed = parseSet(JSON.parse(readFileSync(setPath, 'utf8')));
  if (!parsed.ok) throw new Error(`${setPath} is not a valid set:\n  ${parsed.errors.join('\n  ')}`);
  return parsed.set;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const i = process.argv.indexOf('--set');
  const setPath = i === -1 ? undefined : process.argv[i + 1];
  if (setPath === undefined) {
    process.stderr.write('usage: node scripts/replycases/sql.ts --set <set.json>\n');
    process.exit(2);
  }
  const set = loadSet(setPath);
  writeFileSync(set.sql, renderSql(set, generatedBy(setPath)));
  writeFileSync(set.activationSql, activationFile(set, setPath));
  process.stdout.write(`wrote ${set.sql} (${set.cases.length} cases, inactive) and ${set.activationSql}\n`);
}
