/**
 * Turn the signed platform blocks into a seed migration.
 *
 * `prompt/README.md` has always said "the seed loads the file into `prompt_blocks` with
 * that `reviewed_at`". No such seed existed — the gate was built before the thing it
 * gates, deliberately, and then the blocks arrived and the wire between them did not.
 * This is that wire.
 *
 * ## Why generated rather than hand-written
 *
 * A migration cannot read a file: it runs inside Postgres, from a `.sql` text. So the
 * Mongolian has to be *copied* into SQL, and a copy is exactly what D-020 says will drift
 * — here from the file that carries the native speaker's signature, which is the one copy
 * that means anything.
 *
 * So the copy is mechanical and the drift is a test failure:
 *
 *   - `buildSeedSql()` derives the whole migration from `prompt/platform/*.mn.txt` plus
 *     `prompt/platform-mn-review.json`.
 *   - The CLI writes it to `supabase/migrations/0010_prompt_blocks_seed.sql`.
 *   - `generate-seed.test.ts` asserts the checked-in file equals `buildSeedSql()`, so a
 *     block edited without regenerating fails CI rather than shipping a database whose
 *     text differs from the signed one.
 *
 * The signature still lives on the FILE, not on this output. That ordering matters: the
 * hash signs what a native speaker read, and the migration is downstream of it.
 *
 * Usage: `node scripts/prompt/generate-seed.ts` (writes), `--check` (exit 1 if stale).
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const PLATFORM_DIR = 'prompt/platform';
const SIGNOFF = 'prompt/platform-mn-review.json';
export const SEED_PATH = 'supabase/migrations/0010_prompt_blocks_seed.sql';

/**
 * Dollar-quoting, so nothing in the Mongolian needs escaping and no apostrophe can end a
 * string early. The tag is asserted absent from every body rather than assumed.
 */
const TAG = '$mn$';

/**
 * The compiled prompt's layer, per block. `null` means **not part of the compiled
 * prompt** — the block is customer-visible Mongolian that something else renders.
 *
 * This is a map rather than a filename convention because the two families that are not
 * prompt sections are not distinguishable by name from ones that might be later, and a
 * convention that has to be remembered is the kind D-020 is about.
 */
function layerFor(blockKey: string): 'L0' | null {
  if (blockKey.startsWith('data_deletion_')) return null; // the status page renders these
  if (blockKey === 'comment_public_reply') return null; // a canned_responses template
  // Everything else is the boundary gate: the L0 scaffold, ahead of every tenant section,
  // which is what makes it one cache entry for the whole platform (render.ts's note).
  return 'L0';
}

export type SeedBlock = {
  blockKey: string;
  ordinal: number;
  layer: 'L0' | null;
  body: string;
  reviewedBy: string;
  reviewedAt: string;
};

/** Gate blocks in wire order. `00`/`01` first, then Ш0–Ш9 by their numeric index. */
function gateOrder(blockKey: string): number {
  const sh = /^sh(\d+)_/.exec(blockKey); // ascii-safe: a filename prefix, ASCII by construction
  if (sh !== null) return 100 + Number(sh[1]);
  const numbered = /^(\d+)_/.exec(blockKey); // ascii-safe: as above
  return numbered !== null ? Number(numbered[1]) : 0;
}

export function readSignedBlocks(root = process.cwd()): SeedBlock[] {
  const signoff = JSON.parse(readFileSync(path.join(root, SIGNOFF), 'utf8')) as {
    blocks: { block_id: string; sha256: string; reviewed_by: string; reviewed_at: string }[];
  };
  const byId = new Map(signoff.blocks.map((b) => [b.block_id, b]));

  const files = readdirSync(path.join(root, PLATFORM_DIR))
    .filter((f) => f.endsWith('.mn.txt'))
    .sort();

  const blocks: SeedBlock[] = [];
  for (const file of files) {
    const blockKey = file.slice(0, -'.mn.txt'.length);
    const body = readFileSync(path.join(root, PLATFORM_DIR, file), 'utf8');
    const entry = byId.get(blockKey);
    if (entry === undefined) {
      // check-mn-review.mjs already fails on this; refusing here too means the seed can
      // never be generated from an unsigned block even if the guard is skipped.
      throw new Error(`${file} has no sign-off in ${SIGNOFF}. Refusing to seed unreviewed Mongolian.`);
    }
    if (body.includes(TAG)) throw new Error(`${file} contains ${TAG}, which would end the SQL literal early.`);
    if (body.normalize('NFC') !== body) throw new Error(`${file} is not NFC-normalised.`);
    blocks.push({
      blockKey,
      ordinal: layerFor(blockKey) === null ? 0 : gateOrder(blockKey),
      layer: layerFor(blockKey),
      body,
      reviewedBy: entry.reviewed_by,
      reviewedAt: entry.reviewed_at,
    });
  }
  return blocks;
}

const HEADER = `-- 0010 — the signed platform Mongolian, seeded into \`prompt_blocks\`.
--
-- GENERATED by scripts/prompt/generate-seed.ts from prompt/platform/*.mn.txt and
-- prompt/platform-mn-review.json. Do not edit by hand: scripts/prompt/generate-seed.test.ts
-- regenerates this file and fails if it differs, so a hand-edit is reverted by CI rather
-- than shipped. To change a block, edit the file, have it re-read and re-signed, then run
-- \`node scripts/prompt/generate-seed.ts\`.
--
-- ## The signature lives on the FILE, not on this table
--
-- \`prompt/platform-mn-review.json\` signs each block by the sha256 of the file a native
-- speaker actually read. This migration carries that attribution into the database so the
-- runtime's \`reviewed_at is not null\` gate passes — it does not replace it. If the two
-- ever disagree, the file is right and this file is stale.
--
-- ## Two families here are NOT prompt sections, and \`layer\` says so
--
-- \`layer\` is nullable and null means "customer-visible Mongolian that something other
-- than the prompt compiler renders". Two such families:
--
--   * \`data_deletion_*\` — the eight strings on the data-deletion status page, read by
--     \`src/lib/privacy/statusPage.ts\`. Seeding them is what turns that page from a
--     deliberate 503 into a rendered page.
--   * \`comment_public_reply\` — the TEMPLATE for a per-tenant \`canned_responses\` row.
--
-- **The comment template is not a runtime fallback and must never become one.**
-- \`comments/eligibility.ts\` refuses to post when a tenant has no reviewed line of their
-- own, and that refusal is the whole reason a salon never posts a sentence Dalatech wrote
-- in the salon's voice. This row is what onboarding COPIES from, explicitly, into that
-- tenant's row — which they may then edit, and which carries their own \`reviewed_at\`.
-- A reader that falls back to this row when a tenant's is missing would undo that.
--
-- ADDITIVE ONLY: one nullable column, one partial unique index, and rows in a table that
-- had none.

alter table prompt_blocks
  add column if not exists layer text;

do $$
begin
  if not exists (select 1 from pg_constraint
                 where conrelid = 'prompt_blocks'::regclass and conname = 'prompt_block_layer_known') then
    alter table prompt_blocks add constraint prompt_block_layer_known
      check (layer is null or layer in ('L0', 'L1', 'L2', 'L3'));
  end if;

  -- A tenant row may never occupy a platform layer. \`render.ts\` refuses this at compile
  -- time as \`layer_violation\`; the database refusing it too means a hand-written INSERT
  -- cannot create the row that the renderer would then have to reject.
  if not exists (select 1 from pg_constraint
                 where conrelid = 'prompt_blocks'::regclass and conname = 'prompt_block_layer_matches_scope') then
    alter table prompt_blocks add constraint prompt_block_layer_matches_scope
      check (layer is null
             or (scope = 'platform' and layer in ('L0', 'L1'))
             or (scope = 'tenant'   and layer in ('L2', 'L3')));
  end if;
end $$;

-- One row per platform block key. Two rows sharing a key would reach the renderer as
-- \`ambiguous_order\` — a non-deterministic prefix, which is a cache miss on every request
-- and a different prompt depending on which row sorted first.
create unique index if not exists prompt_blocks_platform_key
  on prompt_blocks (block_key)
  where scope = 'platform' and tenant_id is null;

comment on column prompt_blocks.layer is
  'L0..L3 for a block the prompt compiler renders; NULL for customer-visible Mongolian '
  'rendered by something else (the data-deletion status page, the comment reply template).';
`;

export function buildSeedSql(root = process.cwd()): string {
  const blocks = readSignedBlocks(root);
  const values = blocks
    .map((b) => {
      const layer = b.layer === null ? 'null' : `'${b.layer}'`;
      return (
        `  ('platform', null, '${b.blockKey}', ${b.ordinal}, ${layer},\n` +
        `   ${TAG}${b.body}${TAG},\n` +
        `   '${b.reviewedBy}', '${b.reviewedAt}'::timestamptz)`
      );
    })
    .join(',\n');

  return (
    `${HEADER}\n` +
    `insert into prompt_blocks (scope, tenant_id, block_key, ordinal, layer, body, reviewed_by, reviewed_at)\n` +
    `values\n${values}\n` +
    `on conflict (block_key) where scope = 'platform' and tenant_id is null do update set\n` +
    `  ordinal     = excluded.ordinal,\n` +
    `  layer       = excluded.layer,\n` +
    `  body        = excluded.body,\n` +
    `  reviewed_by = excluded.reviewed_by,\n` +
    `  reviewed_at = excluded.reviewed_at;\n`
  );
}

if (process.argv[1] !== undefined && process.argv[1].endsWith('generate-seed.ts')) {
  const sql = buildSeedSql();
  if (process.argv.includes('--check')) {
    const onDisk = readFileSync(SEED_PATH, 'utf8');
    if (onDisk !== sql) {
      process.stderr.write(`${SEED_PATH} is stale. Run: node scripts/prompt/generate-seed.ts\n`);
      process.exit(1);
    }
    process.stdout.write(`${SEED_PATH} is up to date.\n`);
  } else {
    writeFileSync(SEED_PATH, sql);
    process.stdout.write(`wrote ${SEED_PATH} (${readSignedBlocks().length} blocks)\n`);
  }
}
